image: docker:stable

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

before_script:
  - apk update
  - apk upgrade
  - apk add --update curl && rm -rf /var/cache/apk/*
  - apk add python python-dev py-pip build-base git openssh-client
  - curl -L https://github.com/docker/compose/releases/download/1.8.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
  - chmod +x /usr/local/bin/docker-compose
  - pip install docker-compose
  - mkdir ~/.ssh
  - chmod 700 ~/.ssh
  - eval `ssh-agent -s`
  - ssh root@8.9.5.233

stages:
  - test
  - deploy

test:
  stage: test
  only:
    - development
  script:
    - echo "Run tests in this section"

deploy:
  stage: deploy
  only:
    - master
  script:
    - cp . /root/sites/suggestions-site
    - cd /root/sites/suggestions-site
    - docker-compose build
    - docker-compose up -d
  environment: production
  when: manual
