image: docker:stable

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

before_script:
  - apk update
  - apk upgrade
  - apk add openssh-client bash
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - eval $(ssh-agent -s)
  - ssh-keyscan 8.9.5.233 >> ~/.ssh/known_hosts
  - bash -c 'ssh-add <(echo "$SSH_PRIVATE_KEY")'
stages:
  - test
  - deploy

test:
  stage: test
  only:
    - development
  script:
    - echo "Run tests in this section"
    - scp -r . root@8.9.5.233:/root/sites/suggetions-site
    - ssh -t -t root@8.9.5.233 "cd /root/sites/suggestions-site && sh build.sh"

deploy:
  stage: deploy
  only:
    - master
  script:
    - scp -r . root@8.9.5.233:/root/sites/suggetions-site
    - ssh -t -t root@8.9.5.233 "cd /root/sites/suggestions-site && sh build.sh"
  environment: production
  when: manual
