image: docker:stable

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

before_script:
  - apk update
  - apk upgrade
  # - apk add --update curl && rm -rf /var/cache/apk/*
  # - apk add python python-dev py-pip build-base git
  # - curl -L https://github.com/docker/compose/releases/download/1.8.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
  # - chmod +x /usr/local/bin/docker-compose
  # - pip install docker-compose
  - apk add openssh-client bash
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  # - 'which ssh-agent || apk add openssh-client'
  - eval $(ssh-agent -s)
  # - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - ssh-keyscan 8.9.5.233 >> ~/.ssh/known_hosts
  - bash -c 'ssh-add <(echo "$SSH_PRIVATE_KEY")'
  # - 'which ssh-agent || apk add openssh-client'
  # - eval $(ssh-agent -s) 
  # - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  # - mkdir -p ~/.ssh
  # - chmod 700 ~/.ssh

stages:
  - test
  - deploy

test:
  stage: test
  only:
    - development
  script:
    - echo "Run tests in this section"
    - touch hello_world.txt
    - scp -t -t -r hello_world.txt root@8.9.5.233:/root
    # - ssh -t -t root@8.9.5.233 > touch hello_world.txt
    - echo "Finish tests"

deploy:
  stage: deploy
  only:
    - master
  script:
    - cp . /root/sites/suggestions-site
    - cd /root/sites/suggestions-site
    - docker-compose build
    - docker-compose up -d
  environment: production
  when: manual
