image: docker:stable

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

before_script:
  - apk update
  - apk upgrade
  - apk add openssh-client bash
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - eval $(ssh-agent -s)
  - ssh-keyscan 8.9.5.233 >> ~/.ssh/known_hosts
  - bash -c 'ssh-add <(echo "$SSH_PRIVATE_KEY")'
stages:
  - test
  - deploy

test:
  stage: test
  only:
    - development
  script:
    - echo "Run tests in this section"
    - docker login -u $GL_REG_USER -p $GL_REG_TOKEN registry.gitlab.com
    - echo "Container registry log in successful"

deploy:
  stage: deploy
  only:
    - master
  script:
    - docker login -u $GL_REG_USER -p $GL_REG_TOKEN registry.gitlab.com
    - docker build -t $GL_REG_HOST .
    - docker push $GL_REG_HOST
    - ssh -t -t root@8.9.5.233 "cd /sites/suggestions-site && docker-compose pull && docker-compose up -d"
  environment: production
  when: manual
