version: '3'

services:
    suggestions-site:
      container_name: suggestions-site
      build:
        context: .
        dockerfile: ./Dockerfile
      environment:
        - NODE_ENV=production
      ports:
        - '5000:5000'
      restart: always