version: '3'

services:
    suggestions-site:
      container_name: suggestions-site
      build:
        context: .
        dockerfile: ./Dockerfile
      environment:
        - NODE_ENV=production
      ports:
        - '5000:5000'
      restart: always
      labels:
        traefik.backend: 'suggestions'
        traefik.domain: 'dev-site.suggestionsbot.com'
        traefik.frontend.rule: 'Host:dev-site.suggestionsbot.com'
        traefik.frontend.port: '5000'
        traefik.frontend.entryPoints: 'http,https'
        treafik.frontend.priority: '2'
        traefik.enable: 'true'
      networks:
        - web
networks:
  web:
    external: true